### ISSUE TITLE
Event-emitting commands

### ISSUE THREAD

**Issue by RPiAwesomeness** [CactusDev/CactusBot#215] opened 2017-02-24 22:41 UTC
The idea is that if a certain command is run, the bot will emit an event through Sepal and other people could subscribe to that event feed. This could be useful for integrations like BroBizzleBot's confetti bot or on-stream text being updated by mods

Example syntax: `!command add <name>:<event> <response>`. It would include all arguments in the event as well.

**Comment by 2Cubed** [comment] 2017-02-25 01:05
Alternate syntax idea:

```
!command event add <event> <name> <response...>
```

**Comment by Innectic** [comment] 2017-02-25 04:46
We had talked in our chat a long time ago about doing event `!trigger`s.

```
!trigger add triggerName <triggerCause>
```

Trigger cause could be command being added(removed, changed), same for quotes, etc

**Comment by 2Cubed** [comment] 2017-03-05 06:07
Right! Duplicate of #179.

**Closed by 2Cubed** 2017-03-05 06:07 UTC
