### ISSUE TITLE
Whispering cactusbot a command that requires arguments causes cactusbot to respond to the channel

### ISSUE THREAD

**Issue by EvilNotion** [CactusDev/CactusBot#196] opened 2017-02-08 15:20 UTC
When whispering a command to cactusbot that requires an argument without providing the argument, CactusBot will throw the error out to the chat, rather than the whisper.

![image](https://cloud.githubusercontent.com/assets/24416612/22743434/32e8b14c-ede8-11e6-8f31-dfb603d36402.png)

**Comment by 2Cubed** [comment] 2017-02-08 22:43
Good find! Definitely need to fix this. Thanks for opening an issue, BTW! :)

**Comment by Innectic** [comment] 2017-02-11 05:52
I seem to be unable to reproduce this bug, so I'm assuming it's been fixed at some other point by someone else. Closing for now, feel free to reopen if you're still having issues :D

**Closed by Innectic** 2017-02-11 05:52 UTC
Labels: bug
